services:
  jenkins:
    # --- MODIFICATION ICI ---
    # Au lieu de 'image: ...', on utilise 'build: .'
    build: .
    # image: jenkins/jenkins:lts-jdk17  <-- On commente ou supprime cette ligne
    # ------------------------

    container_name: buy01-jenkins
    user: root
    privileged: true
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
        # --- AJOUT SONARQUBE ---
  sonarqube:
    image: sonarqube:lts-community
    container_name: buy01-sonar
    ports:
      - "9000:9000"
    environment:
      # Désactive les checks stricts pour faciliter le lancement en local
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs

volumes:
  sonar_data:
  sonar_extensions:
  sonar_logs: