services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17 # Version avec Java 17 (important pour nos microservices)
    container_name: buy01-jenkins
    user: root # Nécessaire pour accéder au socket Docker
    privileged: true
    ports:
      - "9090:8080" # Interface Web sur 9090
      - "50000:50000" # Port pour les agents esclaves
    volumes:
      - ./jenkins_home:/var/jenkins_home # Persistance des données
      - /var/run/docker.sock:/var/run/docker.sock # Permet à Jenkins de piloter le Docker de ton Ubuntu
      - /usr/bin/docker:/usr/bin/docker # Donne accès à la commande 'docker'
      - /usr/bin/docker-compose:/usr/local/bin/docker-compose